### PR TITLE
bump jenkins version to make CI green

### PR DESCRIPTION
**Pull request by car-roll**
There might have been a bit of a race condition with the merging of #125  and #129 that is causing build failures on the main branch. Basically, the `edu.umd.cs.findbugs.annotations` package cannot be found.
Bumping the jenkins version solves this issue and makes CI green again.
This is needed for #133 and technically the other outstanding pull requests.

cc @bitwiseman  @jglick 

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by car-roll** [comment]
@bitwiseman friendly ping to take a look at this PR
Would you also be able to grant me write access to this repo? Then I can go cleaning up the remaining PRs. I do have release permissions already on RPU.

**Comment by jglick** [comment]
> I do have release permissions already on RPU.

In that case I think you can ask Jenkins admins to align GH permission with the RPU list.

**Review by jglick — APPROVED** [review]

**Comment by car-roll** [comment]
@jglick thanks! is that just through the dev-mailing list?

**Comment by jglick** [comment]
https://github.com/jenkins-infra/helpdesk/issues/new?labels=github-permissions&template=2-github-permissions.yml I guess.

**Pull request merged**
