### PR TITLE
Bump github-api from 1.99 to 1.101

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Comment by v1v** [comment]
Hi,

I've just seen this version, will this particular bump help with https://github.com/github-api/github-api/issues/539 ? 

Cheers

**Comment by timja** [comment]
Don’t think so, afaik that’s the GitHub api not responding for a few seconds. It happens every now and then

**Comment by v1v** [comment]
Thanks @timja for the clarification. I need to figure out what else we can do in our end to get rid of that 👿 and random issue.

**Comment by timja** [comment]
> Thanks @timja for the clarification. I need to figure out what else we can do in our end to get rid of that 👿 and random issue.

I think more retries / larger exponential backoff either in github-api / github-branch-source-plugin would most likely be what could be done.
note: github-api already retries 3 times with backoff.

**Comment by bitwiseman** [comment]
@timja @v1v  Just hold on.  I'm going to get github-api 1.102 shortly.  1.101 can't be used: see #28

**Comment by timja** [comment]
Not sure how that link relates to why it can’t be used

**Pull request closed without merging**
