### PR TITLE
[JENKINS-31834] Upgrade github-api dependency

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-31834](https://issues.jenkins-ci.org/browse/JENKINS-31834)

to [1.71](https://github.com/kohsuke/github-api/releases/tag/github-api-1.71)

### CODE REVIEW

**Comment by lanwen** [comment]
why it have 2 commits for such simple change? :)

**Comment by recena** [comment]
@lanwen Well it is simple to understand if you read the issue description, specially, [this comment](https://issues.jenkins-ci.org/browse/JENKINS-31834?focusedCommentId=242928&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-242928).

**Comment by recena** [comment]
@lanwen, the PR was squashed.

**Comment by olivergondza** [comment]
@KostyaSha, any objections to release this? It blocks [JENKINS-31827](https://issues.jenkins-ci.org/browse/JENKINS-31827).

**Comment by recena** [comment]
@olivergondza Thanks, it seems your comment had more power than mine :dizzy_face:

**Comment by recena** [comment]
@KostyaSha Thanks so much for your time.

**Comment by KostyaSha** [comment]
@recena @olivergondza did simple things mentioned here https://issues.jenkins-ci.org/browse/JENKINS-31834?focusedCommentId=242927&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-242927

**Comment by recena** [comment]
@KostyaSha Ah ok. I forgot to rename the JIRA issue title and PR title. Sorry for that.

**Pull request merged**
