### PR TITLE
Indentation fixed

### PR DESCRIPTION
**Pull request by recena**
@KostyaSha, What do you think?

@reviewbybees

### CODE REVIEW

**Comment by KostyaSha** [comment]
I see no any reason for such changes.

**Comment by recena** [comment]
@KostyaSha No? I prefer to use the same indentation :dizzy_face: instead of everything mixed.

**Comment by KostyaSha** [comment]
Many projects using tabs, this plugin is a simple wrapper that doesn't expected for mass read, it already contains all required configuration and gets only api version changes.

**Comment by recena** [comment]
@KostyaSha tabs is not the problem, mixed rules are the problem.

Then, Why is there configuration related to m2eclipse plugin? If it is only a simple wrapper...

:+1: to merge this PR and cleanup in other PR.

**Comment by KostyaSha** [comment]
Eclipse has nuances, try follow changes to understand who added it.

**Comment by KostyaSha** [comment]
Normally eclipse related things should be in profile with special variable activation. This block is used in `pluginManagement` so probably some dependent plugin using it.

**Comment by recena** [comment]
@KostyaSha I thought you like the coding style guides and the projects well organized :smile:

**Comment by KostyaSha** [comment]
@recena when this makes sense, this plugin is required only to wrap jar, i see no any problems with its configuration :atm:

**Comment by recena** [comment]
@KostyaSha Makes sense because the indentation is mixed (spaces and tabs).Maybe, you don't have problems, IMO it is very uncomfortable. This is the real problem, never is the right moment.

**Comment by stephenc** [comment]
@recena what's the status of this PR... are you still going forward or are you reworking (perhaps to just fix the tabs for now and worry about applying `mvn tidy:pom` order in a different PR)

**Comment by KostyaSha** [comment]
@stephenc i see no any reasons for merging such changes. Tabs are more flexible, they already exist, pom is not expected for anybody usage as plugin is simple wrapper and @recena do such PRs in every plugin that he is touching.

**Comment by recena** [comment]
I totally disagree with close this PR.

**Comment by recena** [comment]
@stephenc It seems Sr. @KostyaSha made the decission.

Sr. @KostyaSha, I do this PR in order to get coherence.

**Pull request closed without merging**
